### PR TITLE
#63 Residual size vs mag plot

### PR DESCRIPTION
**Pull request by HironaoMiyatake**
This is a pull request for adding a systematic test that plots residual size vs mag plot. This branch has been used for systematic tests with the HSC data, so should be stable enough.

### CODE REVIEW

**Comment by msimet** [comment]
Actually, the same three comments on issue that I just left on #74, sorry!

**Comment by HironaoMiyatake** [comment]
Okay, it works fine. I'll merge this branch.

**Comment by msimet** [comment]
And no comments here--everything looks okay!

**Comment by HironaoMiyatake** [comment]
Thank you for going through the changes! Okay, so this branch is done!

**Pull request merged**
