### PR TITLE
#77b Changes to Correlation Functions

### PR DESCRIPTION
**Pull request by msimet**
Here's the PR for issue #77, requested changes to the default plotting style and docstring for the `CorrelationFunction` systematics tests.  The changes are, briefly:
- Adding units to the x-axis
- Adding a horizontal gray line at 0 to aid the eye
- Changing `xi` to `xi_re`
- Extending the docstring to give the correlation function definitions.

I think this is pretty straighforward, but please do check that the docstring makes sense & everything works on your systems!

### CODE REVIEW

**Comment by msimet** [comment]
Hmm. The list of changes here is showing some things from issue #32, but the diff doesn't show them, so I'm not too worried.  (I had to do some git rebasing due to accidentally branching off #17, so that's probably why.)

**Comment by HironaoMiyatake** [comment]
Looks mostly okay. I found that ylabel is cut out from the frame. Do we want to use tight_layout()?

**Comment by msimet** [comment]
Okay, tried adding this--does it work all right?

**Comment by HironaoMiyatake** [comment]
Sorry for this late response. Hmm, I do not see ylabel yet...
rho1-0009127- 0 3 0 8 1 4 1 8 2 7 2 8 3 8

**Comment by msimet** [comment]
Hmm, that is annoying!  I changed the code to force scientific notation at fewer decimal places--does it look okay now, and do you think those limits are all right?

**Comment by HironaoMiyatake** [comment]
This looks great now! Sorry for this late reply. Please merge this branch into master.

**Pull request merged**
